import {
  Campaign,
  CampaignAssignment,
  Community,
  LedgerTransaction,
  ProofRecord,
  UserProfile,
  Wallet,
  WithdrawalRequest,
} from '@/types';

export const INITIAL_USER_ADVERTISER: UserProfile = {
  id: 'usr_adv_001',
  role: 'ADVERTISER',
  email: 'tunde@swiftpay.ng',
  phone: '+2348012345678',
  full_name: 'Tunde Bakare',
  avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  is_verified: true,
  created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  updated_at: new Date().toISOString(),
};

export const INITIAL_USER_PARTNER: UserProfile = {
  id: 'usr_part_001',
  role: 'COMMUNITY_PARTNER',
  email: 'chioma@unilagpulse.com',
  phone: '+2348098765432',
  full_name: 'Chioma Okonkwo',
  avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  is_verified: true,
  created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
  updated_at: new Date().toISOString(),
};

export const INITIAL_USER_ADMIN: UserProfile = {
  id: 'usr_admin_001',
  role: 'ADMIN',
  email: 'admin@adision.co',
  phone: '+2348000000000',
  full_name: 'ADISION Operations',
  avatar_url: '/brand/logo-square.jpg',
  is_verified: true,
  created_at: new Date(Date.now() - 100 * 86400000).toISOString(),
  updated_at: new Date().toISOString(),
};

export const INITIAL_COMMUNITIES: Community[] = [
  {
    id: 'comm_001',
    owner_id: 'usr_part_001',
    name: 'UNILAG Tech & Campus Deals Hub',
    platform: 'WHATSAPP_GROUP',
    category: 'STUDENTS_CAMPUS',
    invite_link: 'https://chat.whatsapp.com/invite/unilagtechhub01',
    member_count: 2450,
    description: 'The largest active community of tech enthusiasts, gadget buyers, and students in UNILAG.',
    location: 'Lagos, Nigeria',
    verification_image_url: 'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=600&auto=format&fit=crop&q=80',
    status: 'VERIFIED',
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    performance_score: 94.5,
  },
  {
    id: 'comm_002',
    owner_id: 'usr_part_001',
    name: 'Naija Crypto & Forex Signal Lounge',
    platform: 'WHATSAPP_CHANNEL',
    category: 'CRYPTO_WEB3',
    invite_link: 'https://whatsapp.com/channel/naijacryptosignals',
    member_count: 8200,
    description: 'Daily market insights, airdrops, and crypto liquidity discussions across West Africa.',
    location: 'Nigeria (Nationwide)',
    verification_image_url: 'https://images.unsplash.com/photo-1622979135225-d2ba269bc1df?w=600&auto=format&fit=crop&q=80',
    status: 'VERIFIED',
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    performance_score: 89.2,
  },
  {
    id: 'comm_003',
    owner_id: 'usr_part_002',
    name: 'Abuja SME & Business Founders Circle',
    platform: 'WHATSAPP_GROUP',
    category: 'BUSINESS_FINANCE',
    invite_link: 'https://chat.whatsapp.com/invite/abujabusiness02',
    member_count: 1850,
    description: 'Verified SME business owners, wholesalers, and startup operators in the FCT.',
    location: 'Abuja, FCT',
    verification_image_url: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=600&auto=format&fit=crop&q=80',
    status: 'SUBMITTED',
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    performance_score: 82.0,
  },
  {
    id: 'comm_004',
    owner_id: 'usr_part_003',
    name: 'Lagos Thrift & Streetwear Vendors',
    platform: 'WHATSAPP_GROUP',
    category: 'FASHION_LIFESTYLE',
    invite_link: 'https://chat.whatsapp.com/invite/lagosthriftclub',
    member_count: 3100,
    description: 'High-converting fashion buyers, stylists, and thrift vendor network.',
    location: 'Lagos, Nigeria',
    verification_image_url: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=600&auto=format&fit=crop&q=80',
    status: 'VERIFIED',
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    performance_score: 91.0,
  },
];

export const INITIAL_CAMPAIGNS: Campaign[] = [
  {
    id: 'camp_001',
    advertiser_id: 'usr_adv_001',
    title: 'SwiftPay VTU App Launch — Instant 10% Cashback',
    category: 'STUDENTS_CAMPUS',
    ad_copy: `⚡️ NEVER RUN OUT OF DATA AGAIN! ⚡️\n\nGet 1GB Data for just ₦220 on SwiftPay.\nInstant airtime, electricity, and exam pin recharge.\n\n🎁 Use Promo Code: ADISION50 for 10% instant bonus on your first wallet funding!\n\n👇 Click below to download the app and claim now!`,
    media_url: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&auto=format&fit=crop&q=80',
    destination_url: 'https://swiftpay.ng/app-download?src=adision',
    cta_text: 'Download SwiftPay App 📲',
    package_name: 'Growth Blast',
    duration_days: 7,
    budget_amount: 20000,
    commission_rate: 30.0,
    distributable_pool: 14000,
    status: 'ACTIVE',
    payment_status: 'PAID',
    payment_reference: 'PP_REF_984729183',
    total_clicks: 482,
    unique_clicks: 419,
    assigned_count: 3,
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'camp_002',
    advertiser_id: 'usr_adv_001',
    title: 'DevCareers Full-Stack Coding Bootcamp Cohort 6',
    category: 'TECHNOLOGY',
    ad_copy: `🚀 Become a World-Class Software Engineer in 16 Weeks!\n\nApplications are now officially open for Cohort 6.\nScholarships available for top campus applicants.\n\n🔗 Apply today before slots fill up:`,
    media_url: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&auto=format&fit=crop&q=80',
    destination_url: 'https://bootcamp.devcareers.org/apply',
    cta_text: 'Apply for Bootcamp 💻',
    package_name: 'Starter Boost',
    duration_days: 3,
    budget_amount: 7000,
    commission_rate: 30.0,
    distributable_pool: 4900,
    status: 'ACTIVE',
    payment_status: 'PAID',
    payment_reference: 'PP_REF_110294817',
    total_clicks: 164,
    unique_clicks: 147,
    assigned_count: 2,
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_ASSIGNMENTS: CampaignAssignment[] = [
  {
    id: 'asgn_001',
    campaign_id: 'camp_001',
    community_id: 'comm_001',
    assigned_by: 'usr_admin_001',
    tracking_code: 'ad_swift_unilag',
    payout_amount: 4500,
    status: 'PUBLISHED',
    accepted_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    published_at: new Date(Date.now() - 2 * 86400000 + 3600000).toISOString(),
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    campaign: INITIAL_CAMPAIGNS[0],
    community: INITIAL_COMMUNITIES[0],
  },
  {
    id: 'asgn_002',
    campaign_id: 'camp_001',
    community_id: 'comm_004',
    assigned_by: 'usr_admin_001',
    tracking_code: 'ad_swift_thrift',
    payout_amount: 4500,
    status: 'PROOF_SUBMITTED',
    accepted_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    published_at: new Date(Date.now() - 1 * 86400000 + 1800000).toISOString(),
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    campaign: INITIAL_CAMPAIGNS[0],
    community: INITIAL_COMMUNITIES[3],
  },
  {
    id: 'asgn_003',
    campaign_id: 'camp_002',
    community_id: 'comm_001',
    assigned_by: 'usr_admin_001',
    tracking_code: 'ad_dev_unilag',
    payout_amount: 2450,
    status: 'ASSIGNED',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    campaign: INITIAL_CAMPAIGNS[1],
    community: INITIAL_COMMUNITIES[0],
  },
];

export const INITIAL_PROOFS: ProofRecord[] = [
  {
    id: 'proof_001',
    assignment_id: 'asgn_002',
    community_id: 'comm_004',
    submitted_by: 'usr_part_001',
    proof_image_url: 'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=600&auto=format&fit=crop&q=80',
    placement_timestamp: new Date(Date.now() - 24 * 3600000).toISOString(),
    notes: 'Broadcasted to 3,100 active members and pinned for 48 hours.',
    status: 'PENDING',
    submitted_at: new Date(Date.now() - 20 * 3600000).toISOString(),
    assignment: INITIAL_ASSIGNMENTS[1],
    community: INITIAL_COMMUNITIES[3],
  },
];

export const INITIAL_WALLET_PARTNER: Wallet = {
  id: 'wlt_part_001',
  user_id: 'usr_part_001',
  available_balance: 18500,
  pending_balance: 4500,
  lifetime_earned: 42000,
  lifetime_spent: 0,
  currency: 'NGN',
  updated_at: new Date().toISOString(),
};

export const INITIAL_LEDGER_TRANSACTIONS: LedgerTransaction[] = [
  {
    id: 'tx_001',
    wallet_id: 'wlt_part_001',
    user_id: 'usr_part_001',
    transaction_type: 'CAMPAIGN_PAYOUT',
    amount: 4500,
    direction: 'CREDIT',
    balance_after: 18500,
    description: 'Placement payout for SwiftPay UNILAG Campaign',
    status: 'COMPLETED',
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'tx_002',
    wallet_id: 'wlt_part_001',
    user_id: 'usr_part_001',
    transaction_type: 'WITHDRAWAL',
    amount: 15000,
    direction: 'DEBIT',
    balance_after: 14000,
    description: 'Disbursement to GTBank Account (0123***789)',
    status: 'COMPLETED',
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
];

export const INITIAL_WITHDRAWALS: WithdrawalRequest[] = [
  {
    id: 'wdr_001',
    wallet_id: 'wlt_part_001',
    user_id: 'usr_part_001',
    amount: 12000,
    bank_name: 'Guaranty Trust Bank (GTBank)',
    account_number: '0123456789',
    account_name: 'Chioma Okonkwo',
    status: 'REQUESTED',
    created_at: new Date(Date.now() - 4 * 3600000).toISOString(),
  },
];

